### ISSUE TITLE
Attach link to github somewhere in npm

### ISSUE THREAD

**Issue by UzverNumber47** [amativos/react-game-of-life#1]
Hello there!

You did a great job. Please add a link to github somehwere here https://www.npmjs.com/package/node-storage.
Lots of people would like to see the implementation.

**Comment by amativos** [comment]
Hi. I think this is a wrong repository for this issue :) But I did add a repo link to the `node-storage` npm package. Thank you for the suggestion.

**Comment by UzverNumber47** [comment]
oops =)
